name: statemachine
version: 2.0.0

homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.

environment:
  sdk: '>=2.12.0-259.14.beta <3.0.0'
dev_dependencies:
  build_runner: ^1.11.0
  build_web_compilers: ^2.16.0
  test: ^1.16.2
